apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  releaseName: kube-prometheus-stack
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      #version: "4.1.0"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
#  values:
